EOSIO GSG high-level workflow
EOSIO/welcome pull request #419
Opened 2021-04-16 11:44 UTC by bobgt

Embedding a GSG high-level workflow diagram that illustrates the getting started experience.

2021-04-20 11:14 UTC, iamveritas approved these changes

2021-04-21 02:00 UTC, halsaphi approved these changes
Same suggestions as PR 422

2021-04-21 16:55 UTC, lparisc requested changes
Looks good, just fix the broken links.

2021-04-21 16:55 UTC, lparisc commented on docs/30_getting-started-guide/index.md
> +The purpose of the _EOSIO Getting Started Guide_ is to provide guided instructions to set up your local EOSIO development environment and use the environment to build and deploy a basic **_Hello Worl
Suggestion:
development environment and use the environment --> development environment and use it

2021-04-21 16:55 UTC, lparisc commented on docs/30_getting-started-guide/index.md
> +![EOSIO Getting Started Workflow](../eosio-gsg-workflow.png)
This link is broken. Should be:
!\[EOSIO Getting Started Workflow\](eosio-gsg-workflow.png)

2021-04-21 16:55 UTC, lparisc commented on docs/30_getting-started-guide/index.md
> +| Before you begin with the getting started workflow, make sure you familiarize yourself with [EOSIO Platform and Toolchain](../20_introduction-to-eosio/10_platform_and_toolchain.md), [Core Concepts]
The last link is broken. Should be:
\[Technical Features\](../20_introduction-to-eosio/30_technical_features.md)

2021-04-22 15:09 UTC, bobgt commented on docs/30_getting-started-guide/index.md
> +The purpose of the _EOSIO Getting Started Guide_ is to provide guided instructions to set up your local EOSIO development environment and use the environment to build and deploy a basic **_Hello Worl
I tried to be explicit by mentioning "and use the environment..."

The "it" may refer to the "getting started guide" or to the "environment." So to be clear I used "use the environment..."

2021-04-22 15:24 UTC, lparisc approved these changes

2021-04-22 16:09 UTC, merged